version: "3"

services:
  app:
    container_name: hello-world-app
    build: .
    command: npm start
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    environment:
      - ENV_VARIABLE="Frete Rapido"
